**Creación y Indexación:**
1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

4. BONUS: Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [1]:
import numpy as np

In [ ]:
#1. Crea un array 1D con 50 valores aleatorio del 10 al 99. 
a1 = np.random.randint(9,99,(50))
print(a1)
# Accede a los elementos en las posiciones múltiplos de 5.
m5 = a1[::5]
print(f'\n{m5}')


[45 57 53 57 53 40 87 36 66 71  9 71 27 84 97 19 96 66 71 68 35 19 90 20
 84 35 53 20 60 43 36 45 42 15 84 39 33 74 30 38 15 16 18 13 54 64 77 15
 36 72]

[45 40  9 19 35 35 36 39 15 64]


In [15]:
#2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). 
a1_30 = np.random.randint(0,20,(30))
print(a1_30)
# Utiliza indexación para obtener los elementos en las posiciones impares.
impar = a1_30[1::2]
print(f'\n {impar}')

[ 8  4  2 16  5 17 17  8 16  5 18  6 13 10  7  3  2 19  9  6  1 15  2  4
 11  5 14 15 17  7]

 [ 4 16 17  8  5  6 10  3 19  6 15  4  5 15  7]


In [38]:
#3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). 
a_2 = (np.random.randint(0,3,(4,6)))
print(a_2)
a_2f = np.empty(a_2)
# Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

[[0 0 2 1 0 1]
 [2 1 0 1 0 2]
 [1 0 2 1 0 1]
 [0 1 2 0 0 0]]


TypeError: only integer scalar arrays can be converted to a scalar index

In [41]:
#4. BONUS: Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). 
a_3 = np.random.randint(0,101,(2,3,5))
print(a_3)


[[[11 80 51 74 40]
  [51 27  5 52 14]
  [46 98 19  3 29]]

 [[79 94 61 29 24]
  [21 85 88 22 61]
  [53 99 96  4 19]]]


In [ ]:
# Reemplaza los elementos en posiciones múltiplos de 3 por 0.
masc = a_3[::2]
print(masc)
a_masc = np.where(masc,)
print(a_masc)

[[[11 80 51 74 40]
  [51 27  5 52 14]
  [46 98 19  3 29]]]
(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]), array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))


**Reshape y Transpose:**
Ejercicios con reshape:
1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [53]:
#Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive)
a_s3 = np.random.randint(0,101,(2,3,4))
print(a_s3)
#Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.
a2d = np.reshape(a_s3,(4,))
print(a2d)



[[[47 96 51 91]
  [70 19 24 52]
  [45 64 31 43]]

 [[ 8 34 27 86]
  [48 68 72 42]
  [53 69 99 63]]]


ValueError: cannot reshape array of size 24 into shape (4,)